apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 80
      nodePort: 31001
  selector:
    app: result
