apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 31000
  selector:
    app: vote
